export const geeks = [
  {
    id: 1,
    name: "Geek in burgundy playing Super Mario",
    x: 1299,
    y: 326,
    width: 88,
    height: 89,
  },
  {
    id: 2,
    name: "Geek in light green giving a presentation about binary to other geeks",
    x: 910,
    y: 339,
    width: 64,
    height: 140,
  },

  {
    id: 3,
    name: "Geek in blue looking into a portal",
    x: 1080,
    y: 143,
    width: 59,
    height: 103,
  },
  {
    id: 4,
    name: "Geek in blue looking out through a portal",
    x: 1590,
    y: 16,
    width: 57,
    height: 97,
  },
  {
    id: 5,
    name: "Geek in purple wearing a hat watching a robot battle",
    x: 352,
    y: 1406,
    width: 45,
    height: 166,
  },
  {
    id: 6,
    name: "Geek in purple with blue hair bowling with beer bottles",
    x: 1527,
    y: 714,
    width: 129,
    height: 83,
  },
  {
    id: 7,
    name: "Geek in white watching a beer-bottle bowling",
    x: 1339,
    y: 613,
    width: 48,
    height: 141,
  },
  {
    id: 8,
    name: "Geek in a black top with a lambda symbol",
    x: 867,
    y: 1602,
    width: 45,
    height: 80,
  },
  {
    id: 9,
    name: "Geek in a black T-shirt with a bagua symbol",
    x: 230,
    y: 1594,
    width: 56,
    height: 129,
  },
  {
    id: 10,
    name: "Geek in light green sorting rubber balls by color",
    x: 1094,
    y: 864,
    width: 57,
    height: 69,
  },
  {
    id: 11,
    name: "Geek in green watching another geek soldering",
    x: 1794,
    y: 1420,
    width: 55,
    height: 153,
  },
  {
    id: 12,
    name: "Geek in orange soldering a circuit board",
    x: 1883,
    y: 1426,
    width: 85,
    height: 69,
  },
  {
    id: 13,
    name: "Geek in pink cycling with AR glasses on",
    x: 2362,
    y: 1226,
    width: 83,
    height: 141,
  },
  {
    id: 14,
    name: "Geek in olive green working on a laptop in a ball pit",
    x: 1207,
    y: 1020,
    width: 62,
    height: 52,
  },
  {
    id: 15,
    name: "Geek taking a nap in a green sleeping bag",
    x: 1553,
    y: 352,
    width: 86,
    height: 89,
  },
  {
    id: 16,
    name: "Geek in gray looking sad at a laptop",
    x: 998,
    y: 1452,
    width: 53,
    height: 70,
  },
];
